### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by tupoihybbjfiodkxmhcid123456** [anovaguerrero/Panoramic-BlitzNet#1]
Hello, thank you very much for your code, I have a question to ask you, why can't I find the .npy file in the picture, thank you for your answer.
![1666962979446](https://user-images.githubusercontent.com/94735707/198604364-37792d1a-df5f-4c4d-98e8-e06f84164a9d.png)

**Comment by anovaguerrero** [comment]
Hello, thank you for your interest. I have uploaded the missing .npy file to the repository inside the 'Extra' folder.
I hope you can run the code properly now.
