### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by tupoihybbjfiodkxmhcid123456** [anovaguerrero/Panoramic-BlitzNet#2]
Hi, what does the path in the picture mean? Why can't I find it?
![image](https://user-images.githubusercontent.com/94735707/198760222-0b4da4cb-b53d-446f-bd18-7d56ba0ebd34.png)

**Comment by anovaguerrero** [comment]
Hi, you just have to put there the path to the folder where you stored all the files downloaded from the repository. 
Also, in the line 'Change line 86 in sun360.py file with your path to the 'dataset' folder' you have to put inside that .np file your path for the folder named 'dataset'.

An example of path to the files from the repository: cd /home/user/repository (In this case you are supposed to have every file inside the folder 'repository' in your PC).

An example of path to the folder 'dataset': cd /home/user/repository/dataset (In this case you are supposed to have the folder 'dataset' inside the folder 'repository' in your PC).

Hope this explanation is useful. In any case I will keep answering your questions
