### ISSUE TITLE
About the idea and method inside the project

### ISSUE THREAD

**Issue by Jocelyn1267** [anovaguerrero/Panoramic-BlitzNet#3]
I am very interested in the method of processing panoramic images in your project but I cannot understand totally. Could you explain the methods or algorithms and the difference between traditional images and panoramic images in detail please?

**Comment by juliagviu** [comment]
Hi @Jocelyn1267!
Thanks very much for your interest in our work. We kindly refer you to our full paper ["What’s in my Room? Object Recognition on Indoor Panoramic Images"](https://webdiis.unizar.es/~jguerrer/room_OR/room_OR_ICRA2020.pdf), where we explain in detail the method we use and how we adapt it to work successfully for the specific case of panoramic images.
If you have more specific questions, we will be happy to answer them.
