### ISSUE TITLE
May I ask where the standard convolution was replaced with EquiConvs?

### ISSUE THREAD

**Issue by iliuzihao** [anovaguerrero/Panoramic-BlitzNet#4]
Hello, 
I checked the code of your pano_blitznet_model.py and model_utils.py for the model, but I didn't notice where the standard convolution is replaced with EquiConvs, maybe you can explain it to me?

**Comment by juliagviu** [comment]
Hi,

Thanks for your question. Unfortunately, this code base is right now only using standard convolutions. 
Notice this repo is a _re_-implementation of the original _What's in my room_ paper (whose code is not public, as it included not-original licensed software), and therefore it does not contain all the original components of PanoBlitzNet. You can check the original implementation of EquiConvs [here](https://github.com/cfernandezlab/CFL/tree/master), and a re-implementation as a Tensorflow addons package [here](https://github.com/tensorflow/addons/blob/4e86ddd15339de0001649488571a707a2f1f398b/docs/tutorials/deformable_conv2d_ops.ipynb). 

We will be happy to accept new pull requests that extend the current repo to make it more valuable for the community.

Best,
Julia
